# Configuration for Receptionist Bot NLU.
language: en
pipeline:
    - name: WhitespaceTokenizer
    - name: RegexFeaturizer
    - name: CRFEntityExtractor
    - name: EntitySynonymMapper
    - name: CountVectorsFeaturizer
    - name: CountVectorsFeaturizer
    - name: DIETClassifier
      epochs: 300

# Configuration of Policies used
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
  - name: MappingPolicy
